### ISSUE TITLE
Missing app from preview

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Guy-Apell--SEO-Speed---30-June-2022#3]
The TrustedSite app is not coming in preview.
Live: 
![image](https://user-images.githubusercontent.com/97726944/173804746-19c0684b-e064-4ecd-b7e4-7300bbb2f15d.png)

Preview: 
![image](https://user-images.githubusercontent.com/97726944/173804814-5f9a5a89-6ac8-46c0-8da2-b71500d30871.png)

**Comment by devabulabbas** [comment]
When Website will be live it will show automatically

**Comment by Shoaibans** [comment]
> When Website will be live it will show automatically

Okay,  will check once the site go live
